services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: lala
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - backend_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    networks:
      - backend_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./client/.env
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
